### ISSUE TITLE
Add default constructor to class PaperFormat for JSON serialization

### ISSUE THREAD

**Issue by StannieV** [kblok/puppeteer-sharp#1001]
Hi,

I'm trying to serialize and deserialize the PdfOptions class to load pdf options at runtime from a json file. Unfortunately, the class PaperFormat doesn't have a default constructor so an exception occurs when serializing and deserializing the PdfOptions class, Could you please the default constructor to the PaperFormat class so serialize and deserialize is possible?

Example:
```cs
var newPdfOptions = new PdfOptions
{
    Format = PaperFormat.A4,
    DisplayHeaderFooter = true,
    MarginOptions = new MarginOptions
    {
        Top = "20px",
        Right = "20px",
        Bottom = "40px",
        Left = "20px"
    },
    FooterTemplate = "<div id=\"footer-template\" style=\"font-size:10px !important; color:#808080; padding-left:10px\">- <span class=\"pageNumber\"></span> - </div>"
};

var newPdfOptionsValue = JsonConvert.SerializeObject(newPdfOptions); // Newtonsoft.Json

// Produces exception:
var newPdfOptions2 = JsonConvert.DeserializeObject<PdfOptions>(newPdfOptionsValue); //Newtonsoft.Json
```

Produces exception:

Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type PuppeteerSharp.Media.PaperFormat. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'Format.Width', line 1, position 299.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at SmartLink.Function.Reporting.OnDemandAnalysisReporting.OnDemandAnalysisReportingFunction.Run(String message, ILogger log) in C:\git\Smartlink2.0\source\SmartLink.Function.Reporting\OnDemandAnalysisReporting\OnDemandAnalysisReportingFunction.cs:line 54

**Comment by kblok** [comment]
Make sense 👍
