### ISSUE TITLE
Exception when downloading chrome in docker

### ISSUE THREAD

**Issue by psclkhoury** [kblok/puppeteer-sharp#1060]
Hi,

I am trying to run puppeteer sharp in docker (I know it is not fully supported but I found some posts where people made it work) but every time I try to download the browser I get the following exception:

```c#
Exception when downloading the browser: System.DllNotFoundException: Unable to load shared library 'MonoPosixHelper' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libMonoPosixHelper: cannot open shared object file: No such file or directory
   at PuppeteerSharp.Helpers.Linux.LinuxSysCall.FromFilePermissions(FilePermissions value, UInt32& rval)
   at PuppeteerSharp.BrowserFetcher.DownloadAsync(Int32 revision)
   at ADM.Jobs.Program.Main(String[] args) in /usr/src/jobs/Program.cs:line 18
```

This is probably not an issue in PuppeteerSharp, but I was wondering if someone had the same issue and knows how to solve it.

This is the code I am using

```c#
try
{
    await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
}
catch (Exception e)
{
    Console.WriteLine($"Exception when downloading the browser: {e}");
    throw;
}
Console.WriteLine("Browser downloaded!");
```

and this is the docker file:

```docker
FROM microsoft/dotnet:latest
WORKDIR /usr/src
COPY . ./
RUN dotnet build
RUN dotnet publish -o app
ENTRYPOINT ["dotnet", "app/Test.dll"]
```

**Comment by scabana** [comment]
Resolved by https://github.com/kblok/puppeteer-sharp/issues/1035

As for the docker part, you'll need something like this: 

```
RUN apt-get update \
	&& apt-get install -yq libgconf-2-4 \
	&& apt-get install -y gnupg2

#disable this when there's a version of puppeteer-sharp that supports not having mono is released
RUN apt-get install -y apt-transport-https dirmngr gnupg ca-certificates \
	&& apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
	&& echo "deb https://download.mono-project.com/repo/debian stable-stretch main" | tee /etc/apt/sources.list.d/mono-official-stable.list \
	&& apt-get update \
	&& apt-get install -y mono-complete

# Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others)
# Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer
# installs, work.

RUN apt-get update && apt-get install -y wget --no-install-recommends \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge --auto-remove -y curl \
    && rm -rf /src/*.deb 
```

And add your docker stuff after

**Comment by scabana** [comment]
@kblok I don't know if a bug should be opened about the last "RUN", it's used to have add dependencies that your download doesn't pull in... which would be very nice to have without doing other operations... I'm not sure which way is the right way.

**Comment by scabana** [comment]
> I don't think it's something Puppeteer-Sharp should do. We could create a Docker image with this setting.

Or maybe just an example DockerFile would make it much more clear. One thing to note: I think it should point to the same chrome version as the one that will be downloaded in the code (even though we may not be able to know at docker build time). Today, my snippet installs chrome-unstable.

**Comment by psclkhoury** [comment]
Thanks @scabana it worked great. Let's see now if I can generate some pdfs in a docker container.
