### ISSUE TITLE
Request Interception Error in headfull mode

### ISSUE THREAD

**Issue by IliaBrahinets** [kblok/puppeteer-sharp#1146]
Request interception is not working properly with the following snippet:
```csharp
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
var launchOptions = new LaunchOptions
{
    Headless = false,
    Devtools = true
};
var url = "https://google.com";
using (var browser = await Puppeteer.ConnectAsync(launchOptions))
using (var page = (await browser.PagesAsync()).First())
{
    await page.SetRequestInterceptionAsync(true);
    page.Request += async (sender, args) =>
    {
        Console.WriteLine(args.Request.Url);
        await args.Request.ContinueAsync();
    };
    await page.GoToAsync(url);
}
```

### Expected behavior:

Page loading ends up with success.

### Actual behavior:

Thrown the following error:
```csharp
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> PuppeteerSharp.NavigationException: Navigation failed because browser has disconnected! (NetworkManager failed to process Fetch.requestPaused. Value cannot be null.
Parameter name: key.    at System.Collections.Concurrent.ConcurrentDictionary`2.set_Item(TKey key, TValue value)
   at PuppeteerSharp.NetworkManager.<OnRequestPausedAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.NetworkManager.<Client_MessageReceived>d__40.MoveNext()) ---> PuppeteerSharp.TargetClosedException: Navigation failed because browser has disconnected! (NetworkManager failed to process Fetch.requestPaused. Value cannot be null.
Parameter name: key.    at System.Collections.Concurrent.ConcurrentDictionary`2.set_Item(TKey key, TValue value)
   at PuppeteerSharp.NetworkManager.<OnRequestPausedAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at 
...
```
### Versions

*  PuppeteerSharp v1.17.0
* .NET framework 4.7.2

### Additional Information
The problem lies here:
https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/NetworkManager.cs
```csharp
 private async Task OnRequestPausedAsync(FetchRequestPausedResponse e)
{
    if (!_userRequestInterceptionEnabled && _protocolRequestInterceptionEnabled)
    {
        try
        {
            await _client.SendAsync("Fetch.continueRequest", new FetchContinueRequestRequest
            {
                RequestId = e.RequestId
            }).ConfigureAwait(false);
        }
        catch (PuppeteerException ex)
        {
            _logger.LogError(ex.ToString());
        }
    }

    var requestId = e.NetworkId;
    var interceptionId = e.RequestId;
    if (!string.IsNullOrEmpty(requestId) && _requestIdToRequestWillBeSentEvent.TryRemove(requestId, out var requestWillBeSentEvent))
    {
        await OnRequestAsync(requestWillBeSentEvent, interceptionId).ConfigureAwait(false);
    }
    else
    {
       //requestId = null, for some reason
        _requestIdToInterceptionId[requestId] = interceptionId;
    }
}
```
Tested the same snippet with [nodejs_puppeteer](https://github.com/GoogleChrome/puppeteer), with version v1.17.0. Page loaded successfully but also _onRequestPaused method is called with requestId (event.newtorkId) = undefined, the exception is not thrown because **_requestIdToInterceptionId = new Map()** in nodejs implementation, so **Map** just eats null, and undefined key values when **ConcurrentDictionary<string, string>** in C# impl doesn't accept null as a key value.

**Comment by kblok** [comment]
Fixed on v1.17.1
