### ISSUE TITLE
How to disable images to download?

### ISSUE THREAD

**Issue by TTonlyV5** [kblok/puppeteer-sharp#1147]
I tried to use the code, but it didn't work.
```csharp
                   // disable images to download
                    await page.SetRequestInterceptionAsync(true);
                    page.Request += (sender, e) =>
                    {
                        if (e.Request.ResourceType == ResourceType.Image)
                            e.Request.AbortAsync();
                        else
                            e.Request.ContinueAsync();
                    };
```
error like this:
```
Protocol error(Page.navigate): Target closed. (NetworkManager failed to process Fetch.requestPaused. Value cannot be null.
Parameter name: key.    at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.set_Item(TKey key, TValue value)
   at PuppeteerSharp.NetworkManager.OnRequestPausedAsync(FetchRequestPausedResponse e)
   at PuppeteerSharp.NetworkManager.Client_MessageReceived(Object sender, MessageEventArgs e))
```
environment:
```
dotnet core 2.2
vs 2019
```

**Comment by kblok** [comment]
Fixed on v1.17.1

**Comment by TTonlyV5** [comment]
If you use these codes, it will time out. o(︶︿︶)o

**Comment by kblok** [comment]
@TTonlyV5 after upgrading to 1.17.1?

**Comment by TTonlyV5** [comment]
yes，nuget 1.17.1

**Comment by kblok** [comment]
Do you have some code I can use to test?

**Comment by TTonlyV5** [comment]
if i use 1.14.1 ，it work well .

**Comment by kblok** [comment]
@TTonlyV5  Do you have some code I can use to test?

**Comment by TTonlyV5** [comment]
code like this. use local chrome.

```
public static async Task<string> LogInForGetCookieSessionTokenAsync(string LoginUrl = "https://www.baidu.com/")
        {
            try
            {
                string[] ResultCookies = new string[] { };
                //获取用户名
                string UserName = Environment.UserName;

                var currentDirectory = Path.Combine(@"C:\Users\", UserName, @"AppData\Local\Google\Chrome\Application\", "Chrome.exe");//string currentDirectory = Path.GetDirectoryName(@"C:\Users\TT\AppData\Local\Google\Chrome\Application"); //指定Chrome.exe在这目录才行

                if (!File.Exists(currentDirectory))
                {
                    currentDirectory = Path.GetDirectoryName(AppDomain.CurrentDomain.BaseDirectory);
                    var downloadPath = Path.Combine(currentDirectory, "LocalChromium");
                    Console.WriteLine($"Attemping to set up puppeteer to use Chromium found under directory {downloadPath} ");
                    if (!Directory.Exists(downloadPath))
                    {
                        Console.WriteLine("Custom directory not found. Creating directory");
                        Directory.CreateDirectory(downloadPath);

                        Console.WriteLine("Downloading Chromium");

                        var browserFetcherOptions = new BrowserFetcherOptions { Path = downloadPath };
                        var browserFetcher = new BrowserFetcher(browserFetcherOptions);
                        await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);

                        var executablePath = browserFetcher.GetExecutablePath(BrowserFetcher.DefaultRevision);

                        if (string.IsNullOrEmpty(executablePath))
                        {
                            Console.WriteLine("Custom Chromium location is empty. Unable to start Chromium. Exiting.\n Press any key to continue");
                            Console.ReadLine();
                            return "Custom Chromium location is empty. Unable to start Chromium. Exiting.\n Press any key to continue";
                        }
                        Console.WriteLine($"Attemping to start Chromium using executable path: {executablePath}");
                        //Set Path
                        currentDirectory = Path.Combine(executablePath, "Chromium.exe");
                    }
                    else
                    {
                        //Set Path  这里没做下载失败的判断
                        currentDirectory = Path.Combine(downloadPath, "Chromium.exe");
                    }
                }

                var options = new LaunchOptions
                {
                    Headless = true,//无头
                    ExecutablePath = currentDirectory,//本地路径
                    Args = new string[]
                    {
                        "--disable-infobars",//隐藏 自动化标题
                    },//添加Argument 和webdriver一样吧
                    DefaultViewport = new ViewPortOptions
                    {
                        Width = 500,
                        Height = 500,
                        IsMobile = true,
                        //DeviceScaleFactor = 2
                    },
                    //SlowMo=250, // slow down by 250ms
                };

                using (var browser = await Puppeteer.LaunchAsync(options))
                using (var page = await browser.NewPageAsync())
                {              
                    // disable images to download
                    await page.SetRequestInterceptionAsync(true);
                    page.Request += (sender, e) =>
                    {
                        if (e.Request.ResourceType == ResourceType.Image)
                            e.Request.AbortAsync();
                        else
                            e.Request.ContinueAsync();
                    };
                    //设置手机模式
                    await page.SetUserAgentAsync("Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1");
                    //进入登录页
                    await page.GoToAsync(LoginUrl);
                    // 登录
                    Console.WriteLine("Start Login!");
                    await page.GetContentAsync();
                    
                }
                return ResultCookies[0];
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return "";
            }
        }

```

**Comment by kblok** [comment]
@TTonlyV5  Your code is working for me.
Maybe you need to run BrowserFetcher again to get the right Chromium version?

**Comment by TTonlyV5** [comment]
@kblok This code runs correctly on chromuim, but chrome doesn't work. Use 1.14.1 Both can be used.

**Comment by kblok** [comment]
@TTonlyV5 you need at least Chrome 76.0.3786.0

**Comment by TTonlyV5** [comment]
Thank you for your answer. Maybe I misunderstood the versions of chrome and chromium. :-(
