### ISSUE TITLE
await browser.NewPageAsync() throwing an exception

### ISSUE THREAD

**Issue by Wolfthorne** [kblok/puppeteer-sharp#1155]
### Description

When using puppeteer with the task scheduler we are seeing the following exception.
System.InvalidOperationException
  HResult=0x80131509
  Message=An attempt was made to transition a task to a final state when it had already completed.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.TaskCompletionSource`1.SetException(Exception exception)
   at PuppeteerSharp.ChromiumProcess.State.StartingState.<>c__DisplayClass5_0.<StartCoreAsync>g__OnProcessExitedWhileStarting|1(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)

E.g.

```csharp
//items is a list of objects containing 33+ objects
var tasks = items.Select(async t =>
{
    Page page = null;
    Browser browser = null;
    try
    {
        var options = new LaunchOptions { /*  */ };
        var chromiumRevision = BrowserFetcher.DefaultRevision;
        browser = await Puppeteer.LaunchAsync(options, chromiumRevision);
        page = browser.NewPageAsync();

        await page.SetContentAsync(t.html, new NavigationOptions
        {
            WaitUntil = new WaitUntilNavigation[]
            {
                WaitUntilNavigation.Networkidle0
            }
        });

        var stream = await page.ScreenshotStreamAsync();

        //Use stream
    }
    finally
    {
        page?.Browser?.CloseAsync();
        page?.CloseAsync();
    }
}

await System.Threading.Tasks.Task.WhenAll(tasks);
```
### Versions

PuppeteerSharp 1.15.0
.NET framework 4.7.2

**Comment by kblok** [comment]
Good catch. We should be using `TrySetException` and `TrySetResult` across the board.
I'm wondering how come we get a completed task there. I bet that the connection is being closed and the `Close` method completed the task before that call.

**Comment by Wolfthorne** [comment]
I am not sure why? The issue we are getting that resulted in this exception is when we are running 33+ tasks that all open up a new browser. Sometimes it gets stuck on launch browser or newpageasync then this exeption gets thrown.

**Comment by rgroenewoudt** [comment]
We are running into this same issue on production when generating PDFs with Puppeteer. No idea how many are running at the same time.
