### ISSUE TITLE
Exception when Chrome fails to launch

### ISSUE THREAD

**Issue by CommonGuy** [kblok/puppeteer-sharp#128]
If Chrome somehow fails to launch, the puppeteer fails to read the error message. Instead, I get the following exception:

```
Unhandled Exception: System.InvalidOperationException: Cannot mix synchronous and asynchronous operation on process stream.
at System.Diagnostics.Process.get_StandardError()
at PuppeteerSharp.Launcher.<>c__DisplayClass19_0.<WaitForEndpoint>b__0(Object sender, EventArgs e)
at System.Diagnostics.Process.OnExited()
at System.Diagnostics.Process.RaiseOnExited()
at System.Diagnostics.Process.CompletionCallback(Object context, Boolean wasSignaled)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

which occurs at this line: https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Launcher.cs#L241

I think it is because this line https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Launcher.cs#L287 is asynchronous, while the former is synchronous.

**Comment by kblok** [comment]
Thanks for reporting that @CommonGuy. Do you know how we can reproduce that scenario?

**Comment by CommonGuy** [comment]
@kblok Create an executable that fails when you try to start it. Then place it at the chrome executable path. I think that should work...
