### ISSUE TITLE
Protocol error (IO.read): Invalid parameters handle: string value expected

### ISSUE THREAD

**Issue by Saibamen** [kblok/puppeteer-sharp#1295]
### Description

Error while `await page.PdfStreamAsync()` with HeadlessChrome/73.0.3683.75

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

E.g.

```csharp
FROM microsoft/dotnet:2.2-sdk AS build
COPY . .

RUN dotnet build xy.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish xy.csproj -c Release -o /app

FROM base AS final

RUN deps='gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils libappindicator3-1 wget chromium' \
	&& apt-get update && apt-get install -y $deps --no-install-recommends

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "xy.dll"]
```

### Expected behavior:

No error, should receive PDF
### Actual behavior:

[What actually happens]
```
EventMessage: Protocol error (IO.read): Invalid parameters handle: string value expected
StackTrace:    at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback)
at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args)
at PuppeteerSharp.Helpers.ProtocolStreamReader.ReadProtocolStreamByteAsync(CDPSession client, String handle, String path)
at PuppeteerSharp.Page.PdfInternalAsync(String file, PdfOptions options)
at PuppeteerSharp.Page.PdfStreamAsync(PdfOptions options)
```

### Versions

* Which version of PuppeteerSharp are you using? 1.20.0
* Which .NET runtime and version are you targeting? .NET Core 2.2
* HeadlessChrome/73.0.3683.75

**Comment by kblok** [comment]
@Saibamen If you use Puppeteer-Sharp 1.20 you need to use Chromium 77 or higher.
