### ISSUE TITLE
Protocol error(Target.attachToTarget): Target closed. (The remote party closed the WebSocket connection without completing the close handshake.)

### ISSUE THREAD

**Issue by Saibamen** [kblok/puppeteer-sharp#1299]
```
Protocol error(Target.attachToTarget): Target closed. (The remote party closed the WebSocket connection without completing the close handshake.)
at PuppeteerSharp.Connection.SendAsync(String method, Object args, Boolean waitForCallback)
at PuppeteerSharp.Connection.SendAsync[T](String method, Object args)
at PuppeteerSharp.Connection.CreateSessionAsync(TargetInfo targetInfo)
at PuppeteerSharp.Target.CreatePageAsync()
at PuppeteerSharp.Browser.CreatePageInContextAsync(String contextId)
```

```
using (var browser = await Puppeteer.LaunchAsync(launchOptions))
            {
                try
                {
                    using (var page = await browser.NewPageAsync())
```

Bug appears in `using (var page = await browser.NewPageAsync())` line

**Comment by kblok** [comment]
Are you using BrowserFetcher to download a browser or using an existing one?
This looks like a wrong Chrome version.

**Comment by Saibamen** [comment]
Wrong Chrome version
