### ISSUE TITLE
Chromium revision is not downloaded

### ISSUE THREAD

**Issue by Legends** [kblok/puppeteer-sharp#1305]
1. .net 4.8
2. console app (framework)
3. Chrome Version 77.0.3865.120 (Official Build) (64-bit)
4. `Install-Package PuppeteerSharp -Version 1.20.0`

Getting this in  `Main`:

![image](https://user-images.githubusercontent.com/966368/67050567-16d50580-f139-11e9-82c5-07b7e9a2b9c9.png)

Also checked prereqs, but everything is fine.

What else should I do?

**Comment by kblok** [comment]
Did you run DownloadAsync?
Can you share some code?

**Comment by Legends** [comment]
This is all I have in `Main`:

```
  var browser = await Puppeteer.LaunchAsync(new LaunchOptions
  {
       Headless = true
  });
```

**Comment by Legends** [comment]
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Chromium revision is not downloaded. Run BrowserFetcher.DownloadAsync or download Chromium manually
  Source=PuppeteerSharp
  StackTrace:
   at PuppeteerSharp.Launcher.ResolveExecutablePath()
   at PuppeteerSharp.Launcher.GetOrFetchChromeExecutable(LaunchOptions options)
   at PuppeteerSharp.Launcher.<LaunchAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PuppeteerSharpTest.Program.<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PuppeteerSharpTest.Program.<Main>(String[] args)
```

**Comment by kblok** [comment]
If you take a look at some of the examples you'll find out that you need go download chromium first https://github.com/kblok/puppeteer-sharp#generate-pdf-files

**Comment by Legends** [comment]
I put `await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);` in `main` and it took a while before the app was exiting.
The console showed a black screen.

Now when I hit F5 the breakpoints I set won't even be hit.
Something is corrupted now...

But I don't get the error message anymore.

**Comment by Legends** [comment]
@kblok Just one little question:

Are we allowed to remove `await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);` after the default revison has been installed once or does this statement have to be in code all the time?
