### ISSUE TITLE
Failed to launch Chromium! 

### ISSUE THREAD

**Issue by luowenjia1996** [kblok/puppeteer-sharp#1358]
ERROR 2020-01-08 08:02:26,999 [180  ] pplication.VesselRipper.SpiderAppService - 码头:LONG BEACH,CA-STA,失败原因:Failed to launch Chromium! [42480:32268:0108/080224.220:ERROR:message_window.cc(112)] Failed to create a message-only window: 存储不足，无法处理此命令。 (0x8)
[42480:31416:0108/080224.221:ERROR:google_update_settings.cc(246)] Failed opening key Software\Chromium to set usagestats; result: 5
[42480:39196:0108/080224.203:FATAL:status_tray_win.cc(113)] Check failed: atom_. 
Backtrace:
	ovly_debug_event [0x00007FFEC1051252+16183762]
	ovly_debug_event [0x00007FFEC1050832+16181170]
	ovly_debug_event [0x00007FFEC1063383+16257795]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC263AA24+8660195]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC263ADC8+8661127]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC1F4C6DD+1393052]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC1F4C6AB+1393002]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC2435164+6540323]
	IsSandboxedProcess [0x00007FFEC166D4D7+1796059]
	ovly_debug_event [0x00007FFEC135560E+19346830]
	GetHandleVerifier [0x00007FFEC1A1FC63+2062643]
	IsSandboxedProcess [0x00007FFEC166D290+1795476]
	IsSandboxedProcess [0x00007FFEC17EB69C+3361184]
	IsSandboxedProcess [0x00007FFEC17E9E7E+3355010]
	IsSandboxedProcess [0x00007FFEC17E9364+3352168]
	IsSandboxedProcess [0x00007FFEC17E8E36+3350842]
	ovly_debug_event [0x00007FFEC1031EAC+16055852]
	ovly_debug_event [0x00007FFEC102E1C7+16040263]
	ovly_debug_event [0x00007FFEC102DF4F+16039631]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC1F582E7+1441190]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC1DFA0A4+7011]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC1DF9662+4385]
	ovly_debug_event [0x00007FFEC0848247+7758279]
	ovly_debug_event [0x00007FFEC0BA4D7F+11283711]
	ovly_debug_event [0x00007FFEC0847064+7753700]
	ovly_debug_event [0x00007FFEC0849C08+7764872]
	ovly_debug_event [0x00007FFEC08459EC+7747948]
	ovly_debug_event [0x00007FFEC0FCD3E1+15643489]
	ovly_debug_event [0x00007FFEC0FCDD67+15645927]
	ovly_debug_event [0x00007FFEC0FCDACD+15645261]
	ovly_debug_event [0x00007FFEC0FF8F28+15822504]
	ovly_debug_event [0x00007FFEC0FCD35E+15643358]
	ChromeMain [0x00007FFEC00E11BD+293]
	Ordinal0 [0x00007FF7A7D5275F+10079]
	Ordinal0 [0x00007FF7A7D5182D+6189]
	GetHandleVerifier [0x00007FF7A7E5B7C2+697538]
	BaseThreadInitThunk [0x00007FFF02A084D4+20]
	RtlUserThreadStart [0x00007FFF04E7E8B1+33]

,   at PuppeteerSharp.ChromiumProcess.State.StartingState.StartCoreAsync(ChromiumProcess p)
   at PuppeteerSharp.ChromiumProcess.State.StartingState.StartCoreAsync(ChromiumProcess p)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at CO.Spider.Application.VesselRipper.SpiderAppService.CreateBrowser(CarrierConfigs item, CrawConfig crawConfig, LaunchOptions options) in D:\project\Cityocean\CO.Spider\src\CO.Spider.Application\Spider\SpiderAppService.cs:line 234
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext),重试次数:2
PuppeteerSharp.ChromiumProcessException: Failed to launch Chromium! [42480:32268:0108/080224.220:ERROR:message_window.cc(112)] Failed to create a message-only window: 存储不足，无法处理此命令。 (0x8)
[42480:31416:0108/080224.221:ERROR:google_update_settings.cc(246)] Failed opening key Software\Chromium to set usagestats; result: 5
[42480:39196:0108/080224.203:FATAL:status_tray_win.cc(113)] Check failed: atom_. 
Backtrace:
	ovly_debug_event [0x00007FFEC1051252+16183762]
	ovly_debug_event [0x00007FFEC1050832+16181170]
	ovly_debug_event [0x00007FFEC1063383+16257795]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC263AA24+8660195]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC263ADC8+8661127]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC1F4C6DD+1393052]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC1F4C6AB+1393002]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC2435164+6540323]
	IsSandboxedProcess [0x00007FFEC166D4D7+1796059]
	ovly_debug_event [0x00007FFEC135560E+19346830]
	GetHandleVerifier [0x00007FFEC1A1FC63+2062643]
	IsSandboxedProcess [0x00007FFEC166D290+1795476]
	IsSandboxedProcess [0x00007FFEC17EB69C+3361184]
	IsSandboxedProcess [0x00007FFEC17E9E7E+3355010]
	IsSandboxedProcess [0x00007FFEC17E9364+3352168]
	IsSandboxedProcess [0x00007FFEC17E8E36+3350842]
	ovly_debug_event [0x00007FFEC1031EAC+16055852]
	ovly_debug_event [0x00007FFEC102E1C7+16040263]
	ovly_debug_event [0x00007FFEC102DF4F+16039631]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC1F582E7+1441190]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC1DFA0A4+7011]
	RelaunchChromeBrowserWithNewCommandLineIfNeeded [0x00007FFEC1DF9662+4385]
	ovly_debug_event [0x00007FFEC0848247+7758279]
	ovly_debug_event [0x00007FFEC0BA4D7F+11283711]
	ovly_debug_event [0x00007FFEC0847064+7753700]
	ovly_debug_event [0x00007FFEC0849C08+7764872]
	ovly_debug_event [0x00007FFEC08459EC+7747948]
	ovly_debug_event [0x00007FFEC0FCD3E1+15643489]
	ovly_debug_event [0x00007FFEC0FCDD67+15645927]
	ovly_debug_event [0x00007FFEC0FCDACD+15645261]
	ovly_debug_event [0x00007FFEC0FF8F28+15822504]
	ovly_debug_event [0x00007FFEC0FCD35E+15643358]
	ChromeMain [0x00007FFEC00E11BD+293]
	Ordinal0 [0x00007FF7A7D5275F+10079]
	Ordinal0 [0x00007FF7A7D5182D+6189]
	GetHandleVerifier [0x00007FF7A7E5B7C2+697538]
	BaseThreadInitThunk [0x00007FFF02A084D4+20]
	RtlUserThreadStart [0x00007FFF04E7E8B1+33]

   at PuppeteerSharp.ChromiumProcess.State.StartingState.StartCoreAsync(ChromiumProcess p)
   at PuppeteerSharp.ChromiumProcess.State.StartingState.StartCoreAsync(ChromiumProcess p)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at CO.Spider.Application.VesselRipper.SpiderAppService.CreateBrowser(CarrierConfigs item, CrawConfig crawConfig, LaunchOptions options) in D:\project\Cityocean\CO.Spider\src\CO.Spider.Application\Spider\SpiderAppService.cs:line 234
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
ERROR 2020-01-08 08:02:27,289 [125  ] pplication.VesselRipper.SpiderAppService - 码头:LONG BEACH,CA-STA,失败原因:Failed to create connection,   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at CO.Spider.Application.VesselRipper.SpiderAppService.CreateBrowser(CarrierConfigs item, CrawConfig crawConfig, LaunchOptions options) in D:\project\Cityocean\CO.Spider\src\CO.Spider.Application\Spider\SpiderAppService.cs:line 234
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext),重试次数:2
PuppeteerSharp.ChromiumProcessException: Failed to create connection ---> System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。. ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at PuppeteerSharp.Transport.WebSocketTransport.CreateDefaultWebSocket(Uri url, IConnectionOptions options, CancellationToken cancellationToken)
   at PuppeteerSharp.Transport.WebSocketTransport.CreateDefaultTransport(Uri url, IConnectionOptions connectionOptions, CancellationToken cancellationToken)
   at PuppeteerSharp.Connection.Create(String url, IConnectionOptions connectionOptions, ILoggerFactory loggerFactory, CancellationToken cancellationToken)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   --- End of inner exception stack trace ---
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at CO.Spider.Application.VesselRipper.SpiderAppService.CreateBrowser(CarrierConfigs item, CrawConfig crawConfig, LaunchOptions options) in D:\project\Cityocean\CO.Spider\src\CO.Spider.Application\Spider\SpiderAppService.cs:line 234
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)

**Comment by kblok** [comment]
That seems to be a problem of Chromium in the OS you are executing it.

**Comment by luowenjia1996** [comment]
Should I use chrome to replace chromium in PuppeteerSharp 2.0 instead of the default vesion？

**Comment by kblok** [comment]
It should work with the Chromium downloaded by the app. Did you try opening that chromium manually?

**Comment by luowenjia1996** [comment]
yep,I tried turning that chrome on manually,Maybe I open too many browsers by the app..

**Comment by luowenjia1996** [comment]
ERROR 2020-01-15 09:01:59,890 [88   ] pplication.VesselRipper.SpiderAppService - 船东:SITC,失败原因:Timed out after 30000 ms while trying to connect to Chromium!,   at PuppeteerSharp.ChromiumProcess.State.StartingState.StartCoreAsync(ChromiumProcess p)
   at PuppeteerSharp.ChromiumProcess.State.StartingState.StartCoreAsync(ChromiumProcess p)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at CO.Spider.Application.VesselRipper.SpiderAppService.CreateBrowser(CarrierConfigs item, CrawConfig crawConfig, LaunchOptions options) in D:\project\Cityocean\CO.Spider\src\CO.Spider.Application\Spider\SpiderAppService.cs:line 239
   at Polly.AsyncPolicy.<>c__DisplayClass40_0.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by SuperDaveOsbourne** [comment]
Moving to Puppeteer Sharp 2.0 from 1.2, Windows 10 I get an error in winforms that says. "Unable to find locale data files. Please reinstall. Ver 1.2 acts correctly. 

LaunchOptions options = new LaunchOptions
            {
                Headless = false,
                Devtools = false,
                UserDataDir = Path.Combine(".", "C:\\downloads\\data-dir")
            };


This exception was originally thrown at this call stack:
	PuppeteerSharp.Helpers.TaskHelper.WithTimeout<T>(System.Threading.Tasks.Task<T>, System.TimeSpan, System.Func<System.TimeSpan, System.Exception>)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	PuppeteerSharp.Browser.WaitForTargetAsync(System.Func<PuppeteerSharp.Target, bool>, PuppeteerSharp.WaitForOptions)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
	PuppeteerSharp.Launcher.LaunchAsync(PuppeteerSharp.LaunchOptions)
Inner Exception 1:
ChromiumProcessException: Failed to create connection
Inner Exception 2:
TimeoutException: Timeout of 30000 ms exceeded

**Comment by kblok** [comment]
That error seems to come from Chrome itself. Could you try re-downloading chromium?

**Comment by SuperDaveOsbourne** [comment]
Uninstalled reinstalled. Chromium runs fine from the desktop. 

15.0.875.0 (Developer Build 100012 Windows)

**Comment by SuperDaveOsbourne** [comment]
The solution for me was to reboot the machine and delete everything in the debug directory before running VS. Not sure why, but it looks like Visual Studio was hanging on to some files. 'Clean Solution' sometimes isn't totally clean?  Thanks for all the hard work!
