### ISSUE TITLE
SetContentAsync throws exception on large text streams

### ISSUE THREAD

**Issue by dantheman999301** [kblok/puppeteer-sharp#230]
I've attached a simple repro project sample but it's a rather simple setup.

If you create a large HTML file (I've been using one around 100KB), and read the file in as text, when you try and use this with `SetContentAsync` it will throw the following exception:
```
PuppeteerSharp.MessageException: The connection with the server was terminated abnormally ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.TaskQueue.<Enqueue>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Connection.<SendAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Session.<SendAsync>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Session.<SendAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at PuppeteerSharp.ExecutionContext.<EvaluateHandleAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.ExecutionContext.<EvaluateFunctionHandleAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.ExecutionContext.<EvaluateAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Frame.<EvaluateFunctionAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task ta
sk)
   at PuppeteerSharp.Page.<SetContentAsync>d__113.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharpTest.Program.<Main>d__0.MoveNext() in c:\\dev\\PuppeteerSharpTest\\PuppeteerSharpTest\\Program.cs:line 20"
```

I have also tried `GoToAsync` which throws the same error (you can see this in the attached project).

I've tried using the same file with the nodejs puppeteer library and this works fine, so I don't think it's Chrome limitation on what you can send. 

[PuppeteerSharpTest.zip](https://github.com/kblok/puppeteer-sharp/files/2008715/PuppeteerSharpTest.zip)

**Comment by kblok** [comment]
thank you for the info and the project @dantheman999301.

I'll check this up as soon as a I finished with some connection leaks I'm working on.

**Comment by kblok** [comment]
@dantheman999301 what remote browser are you using?

**Comment by dantheman999301** [comment]
I've been using [Browserless](https://github.com/joelgriffith/browserless/)

I just tried it by running a Chrome instance locally and it works fine.

Now I'm not sure where the issue lies, as the node version of puppeteer can communicate with Browserless fine (even with a large payload for SetContent).

I might be able to get some logs from the container to see if it's aborting the connection from that side.

**Comment by kblok** [comment]
@dantheman999301 let me know what you find. It very important for me to know the limitations and weird scenarios.
