### ISSUE TITLE
browser.NewPageAsync() dies in IIS

### ISSUE THREAD

**Issue by norbertK** [kblok/puppeteer-sharp#375]
I have an Angular Client App with a C# backend. I want to take a screenshot of my webpage on the server.

When I run the following code on my Client (Win10, Visual Studio Professional 2017) everything works fine:

await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
try
{
                var browser = await Puppeteer.LaunchAsync(new LaunchOptions  { Headless = true });
                var page = await browser.NewPageAsync();
                await page.GoToAsync(url);
                await page.ScreenshotAsync(outputFile);
}
catch (Exception e)
{
                SystemLoggerFa...Error(SourceName, null, "Puppeteer failed", e);
}

I then deploy the application to IIS on our Windows Server 2012 R2. Here the program dies at
                var page = await browser.NewPageAsync();
with 

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.CDPSession.<SendAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Page.<CreateAsync>d__157.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Target.<PageAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.Compile

I tried to run it in Visual Studio on the server: works
I used runas to use the IIS service account, to start Visual Studio : works

Only when in IIS, the program dies

Any ideas?

regards
Norbert

**Comment by kblok** [comment]
We have another report related to the NewPageAsync here #374 

You can inject a Logger into the LaunchAsync function. Maybe if you can get those logs into a file, that might be helpful. 

I'm thinking how can I reproduce it.

**Comment by kblok** [comment]
Is your url something I can navigate to? or is a private site?

**Comment by norbertK** [comment]
Still on our dev server behind firewall, sorry

Will try on another server tomorrow

**Comment by kblok** [comment]
@norbertK could you try 1.5?

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by taz4270** [comment]
This bug continues to exist, i'm having this issue now, unfortunatly, i dont know how to make a logger so i could know a bit more
