### ISSUE TITLE
Unauthorized access.

### ISSUE THREAD

**Issue by Dustymcp** [kblok/puppeteer-sharp#376]
### Description
Install from nuget, try out screenshot capture, end with authorization error:
System.UnauthorizedAccessException: 'Access to the path 'C:\Program Files (x86)\IIS Express\.local-chromium' is denied.'

###Code used
```
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true
            });
            var page = await browser.NewPageAsync();
            await page.GoToAsync("http://www.google.com");
            await page.SetViewportAsync(new ViewPortOptions
            {
                Width = 500,
                Height = 500,
            });
            await page.ScreenshotAsync("C:\\puppeteertests", new ScreenshotOptions
            {

                Quality = 100,
                Type = "png"
            });
            await browser.CloseAsync();
```

### Expected behavior:

Starting chromium browser taking screenshot

### Actual behavior:
System.UnauthorizedAccessException: 'Access to the path 'C:\Program Files (x86)\IIS Express\.local-chromium' is denied.'

Program being denied, there is no file named .local-chromium inside folder.
### Versions
NET framework 4.6.1

### Additional Information
Let me know if im doing something wrong or if i missed the installation notes.

**Comment by kblok** [comment]
I would use a folder where you know the process will be able to write files.

```cs
var browserFetcher = new BrowserFetcher(new BrowserFetcherOptions
{
    DownloadsFolder = "C:\SomeFolderWithWriteAccess"
});

await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
    Headless = true,
    ExecutablePath = browserFetcher.RevisionInfo(BrowserFetcher.DefaultRevision).ExecutablePath
});
var page = await browser.NewPageAsync();
await page.GoToAsync("http://www.google.com");
await page.SetViewportAsync(new ViewPortOptions
{
    Width = 500,
    Height = 500,
});
await page.ScreenshotAsync("C:\\puppeteertests", new ScreenshotOptions
{

    Quality = 100,
    Type = "png"
});
await browser.CloseAsync(); 
```

**Comment by Dustymcp** [comment]
Thank you this will come in handy later for CI, my issue was easily resolved by running vs as administrator.

**Comment by JakupGuven** [comment]
@kblok 
I have the same problem as Dusty. 

I used your code: 
```
var browserFetcher = new BrowserFetcher(new BrowserFetcherOptions
            {
                Path = Path.GetTempPath()
            });

            await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                ExecutablePath = browserFetcher.RevisionInfo(BrowserFetcher.DefaultRevision).ExecutablePath
            });
```
But I get a Chrome system error 
 
![image](https://user-images.githubusercontent.com/17982889/65036472-cb69e480-d94b-11e9-89af-dcd8591c4be6.png)

When I use the default ExecutablePath instead, I get this exception:
```System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.217.168.240:443
...  at PuppeteerSharp.BrowserFetcher.<DownloadAsync>d__25.MoveNext()
```

**Comment by Olegkravec** [comment]
Hey guys, 
I have problem with UnauthorizedAccessException...
I should create an app that should be installed to C:\ disk, for example in ...\AppData\Roaming, but there is problem that when app is starting in moment system is booting(autoboot) I always catch this exception:
```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.Directory.InternalCreateDirectory(System.String, System.String, System.Object, Boolean)
   at System.IO.DirectoryInfo.Create()
   at PuppeteerSharp.BrowserFetcher+<DownloadAsync>d__25.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BrowserStack.BrowserStack+<loadBrowserStack>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
As I saw I always catch this exception when app is started by system, when I do manual click "Open" - all ok.
I tryed to autoboot my app from %TMP%, MyDocuments, Roaming and always got error :(
Also I tried to do by this two steps: pre-load .local-chrome folder before autoload, and load in autoload moment.

How to solve this problem?
