### ISSUE TITLE
Error converting value "verbose" to type 'PuppeteerSharp.ConsoleType'. Path 'params.entry.level'. ---> System.ArgumentException: Requested value 'verbose' was not found.

### ISSUE THREAD

**Issue by darkguy2008** [kblok/puppeteer-sharp#519]
**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp).

### Description

When connecting to a website using GoToAsync(), the code doesn't go through because it throws this exception:

```
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value "verbose" to type 'PuppeteerSharp.ConsoleType'. Path 'params.entry.level'. ---> System.ArgumentException: Requested value 'verbose' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at PuppeteerSharp.Page.Client_MessageReceived(Object sender, MessageEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### Complete minimal example reproducing the issue

This will take too much time for me. The actual solution would be to add "Verbose" in the ConsoleType Enum. Sadly, I don't even know what/how to do it myself, but that could solve the issue.

### Expected behavior:

The code will keep going

### Actual behavior:

It crashes

### Versions

* Which version of PuppeteerSharp are you using?
1.4.0

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
netcoreapp2.1

### Additional Information

I'm trying with home router login pages. The error seems to happen when a console message wants/needs to be output with "verbose" level, which makes PuppeteerSharp crash.

**Comment by darkguy2008** [comment]
Yup, this fixed it:

![image](https://user-images.githubusercontent.com/6304136/43618687-027d2c1a-9687-11e8-8c75-48babe614ecc.png)

**Comment by kblok** [comment]
Cool, we’ll fix it.

**Comment by Meir017** [comment]
@darkguy2008 could you please add a code sample to reproduce this issue and cover it with a test?

**Comment by darkguy2008** [comment]
@Meir017 I'd love to but I have no way to provide one as I'm trying with custom websites (home routers login pages), and besides I don't have much time for that. What I can confirm is that I was able to continue developing my app so the fix is 100% guaranteed to work.

**Comment by dredav** [comment]
I'm ran into the same issue. Is the 1.5 release already planned for a date?

**Comment by kblok** [comment]
@dredav we have only the Workers feature left (https://github.com/kblok/puppeteer-sharp/projects/20)
I soon as we finish that feature we'll release 1.5. Could be this weekend or early next week.
