### ISSUE TITLE
EvaluationFailedException on any Evaluation of javascript (Linux)

### ISSUE THREAD

**Issue by HarpyWar** [kblok/puppeteer-sharp#642]
### Description

Any `Evaluate*` method throws exception on Linux, but works fine on WIndows.

### Complete minimal example reproducing the issue

```csharp
var options = new LaunchOptions { 
   Headless = true,
   Args = new[] { "--no-sandbox" } // required for root user
};
var chromiumRevision = BrowserFetcher.DefaultRevision;
var browser = await Puppeteer.LaunchAsync(options, chromiumRevision);
var page = browser.NewPageAsync();

// execute simple js function which returns "123"
var a = await page.EvaluateFunctionAsync<int>("() => 123");
Console.WriteLine(a);
```

// Act
```
PuppeteerSharp.EvaluationFailedException: Protocol error (Runtime.evaluate): Session closed. Most likely the Page has been closed. ---> System.Exception: Protocol error (Runtime.evaluate): Session closed. Most likely the Page has been closed.
   at PuppeteerSharp.CDPSession.SendAsync(String method, Boolean rawContent, Object args)
   at CallSite.Target(Closure , CallSite , Object )
   at PuppeteerSharp.ExecutionContext.EvaluateHandleAsync(String method, Object args)
   at PuppeteerSharp.ExecutionContext.EvaluateExpressionHandleAsync(String script)
   --- End of inner exception stack trace ---
   at PuppeteerSharp.ExecutionContext.EvaluateExpressionHandleAsync(String script)
   at PuppeteerSharp.ExecutionContext.EvaluateAsync[T](Task`1 handleEvaluator)
   at PuppeteerSharp.Frame.EvaluateExpressionAsync(String script)
   at Headless.Program.Run(Int32 id) in /home/headless/net/Program.cs:line 274
```

// Assert
```
123
```

### Versions
puppeteer-sharp 1.6.2 from nuget

dotnet 2.1.402

### Additional Information

Tested on Debian 9 ([dotnet core install instructions](https://www.microsoft.com/net/download/linux-package-manager/debian9/sdk-current))

Also I tried build the latest source code, but I don't know how to do it correctly for this project and build fails:
```
# dotnet build
...
/usr/share/dotnet/sdk/2.1.402/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/headless/puppeteer-sharp/lib/PuppeteerSharp.Tests.CloseMe/PuppeteerSharp.Tests.CloseMe.csproj]
/usr/share/dotnet/sdk/2.1.402/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/headless/puppeteer-sharp/lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj]
/usr/share/dotnet/sdk/2.1.402/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/headless/puppeteer-sharp/lib/PuppeteerSharp.Tests.DumpIO/PuppeteerSharp.Tests.DumpIO.csproj]
/usr/share/dotnet/sdk/2.1.402/Microsoft.Common.CurrentVersion.targets(4533,5): error MSB3030: Could not copy the file "/home/headless/puppeteer-sharp/lib/PuppeteerSharp.TestServer/testCert.cer" because it was not found. [/home/headless/puppeteer-sharp/lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj]
    0 Warning(s)
    4 Error(s)
```

**Comment by kblok** [comment]
Could you try awaiting `NewPageAsync`?

```cs
var page = await browser.NewPageAsync();
```

**Comment by HarpyWar** [comment]
Actually my code uses `await` keywords everywhere, including `NewPageAsync` method. It was just a mistake in my example code.

**Comment by kblok** [comment]
About building issues. As we have many target frameworks in different projects, you would need to build them individually.

Regarding this error:
>/usr/share/dotnet/sdk/2.1.402/Microsoft.Common.CurrentVersion.targets(4533,5): error MSB3030: Could not copy the file "/home/headless/puppeteer-sharp/lib/PuppeteerSharp.TestServer/testCert.cer" because it was not found. [/home/headless/puppeteer-sharp/lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj]
    0 Warning(s)

You need to create a self-signed certificate to be able to run the test server. I didn't dig into that yet. So I would appreciate some help creating that file so that we can set up a CI in Linux. See https://github.com/kblok/puppeteer-sharp/issues/429

**Comment by kblok** [comment]
Closing because we know there is some job to be done on Linux.
