### ISSUE TITLE
JsonSerializationException Error converting value "Ping" to type 'PuppeteerSharp.ResourceType'

### ISSUE THREAD

**Issue by ahazelwood** [kblok/puppeteer-sharp#648]
### Description

I am playing around with puppeteersharp and used google as a good example test site.  During testing, it appears there is not a way to prevent internal exceptions from crashing the process.

### Complete minimal example reproducing the issue

```csharp
       public static async Task DownloadUrl(string url) {
            try {
                var browserOptions = new BrowserFetcherOptions();
                await new BrowserFetcher(browserOptions).DownloadAsync(BrowserFetcher.DefaultRevision);
                var browser = await Puppeteer.LaunchAsync(new LaunchOptions {
                    Headless = true,
                    KeepAliveInterval = 0
                });
                var page = await browser.NewPageAsync();
                await page.SetBypassCSPAsync(true);
                await page.SetViewportAsync(new ViewPortOptions {
                    Width = 1200,
                    Height = 768
                });
                await page.SetUserAgentAsync(UserAgents.Chrome_Windows7_x64);
                var navigationOptions = new NavigationOptions {
                    Timeout = 60 * 1000
                };
                await page.SetRequestInterceptionAsync(true);
                page.Request += Page_Request;
                await page.GoToAsync(url, navigationOptions);
                page.DOMContentLoaded += Page_DOMContentLoaded;
                //var html = await page.EvaluateExpressionAsync(@"function() { var root = document.getElementsByTagName('html')[0]; var html = root ? root.outerHTML : document.body.innerHTML; return html; }");
                //Console.WriteLine("===================================================");
                //Console.WriteLine(html);
                var content = await page.GetContentAsync();
                var cookies = await page.GetCookiesAsync();
                Console.WriteLine("====================================================");
                Console.WriteLine(content);

            }
            catch (Exception ex) {
                Console.Write(ex);
            }
        }

        private static void Page_DOMContentLoaded( object sender, EventArgs e ) {
            Console.WriteLine("Page DOM Content loaded");
        }

        private static async void Page_Request( object sender, RequestEventArgs e ) {
            try {
                Console.WriteLine($"Requesting => {e.Request.Url}");
                if ( e.Request.ResourceType == ResourceType.Script)
                    await e.Request.AbortAsync();
                else
                    await e.Request.ContinueAsync();
            }
            catch (Exception ex) {
                Console.WriteLine($"Error => {ex.Message}");
                await e.Request.ContinueAsync();
            }
        }

        static void Main( string[] args ) {
            try {
                Task.Run( () => Program.DownloadUrl("https://www.google.com/search?q=firewall&oq=firewall&ie=UTF-8") ).GetAwaiter().GetResult();
            }
            catch (Exception ex) {
                Console.WriteLine(ex);
            }
        }
```

### Expected behavior:

I would expect the process to run correctly and any unhandled exceptions to be capable of being captured and handled (for example to ignore them).

### Actual behavior:

```
Requesting => https://www.google.com/search?q=firewall&oq=firewall&ie=UTF-8
Requesting => https://www.google.com/images/hpp/shield_privacy_checkup_green_2x_web_96dp.png
Requesting => https://www.google.com/logos/doodles/2018/us-voter-registration-day-2018-5442282470768640-s.png
Requesting => https://ssl.gstatic.com/gb/images/i1_1967ca6a.png
Requesting => https://www.gstatic.com/ui/v1/activityindicator/loading_24.gif
Requesting => https://ssl.gstatic.com/ui/v1/disclosure/grey-disclosure-arrow-up-down.png
Requesting => https://ssl.gstatic.com/dictionary/static/sounds/20160317/firewall--_us_1.mp3
Requesting => https://www.google.com/images/nav_logo242.png
Requesting => https://www.google.com/xjs/_/js/k=xjs.s.en_US.MqQ_Dv2WfdY.O/m=sx,Fkg7bd,HcFEGb,IvlUe,MC8mtf,OF7gzc,RMhBfe,T4BAC,TJw5qb,TbaHGc,Y33vzc,cdos,cr,elog,hsm,iDPoPb,jsa,mvYTse,r,tg8oTe,uz938c,vWNDde,ws9Tlc,xpltpb,yQ43ff,d,csi/am=AsIizKcPAPJ_SgcLBDAFExaYQMEgEg/rt=j/d=1/dg=2/rs=ACT90oHlf0IPIoG-hjxDGuPBWGkzvseuKg

Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Error converting value "Ping" to type 'PuppeteerSharp.ResourceType'. Path 'params.resourceType'. ---> System.ArgumentException: Requested value 'Ping' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at PuppeteerSharp.NetworkManager.Client_MessageReceived(Object sender, MessageEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### Versions

* Which version of PuppeteerSharp are you using? 1.7.0
* Which .NET runtime and version are you targeting? .NET Core 2.1

**Comment by kblok** [comment]
Thank you @ahazelwood for the detailed description. We'll take a look at that.
