### ISSUE TITLE
One or more errors occurred. (Protocol error(Page.printToPDF): Target closed.

### ISSUE THREAD

**Issue by sudheerkaku** [kblok/puppeteer-sharp#809]
Unhandled Exception: System.AggregateException: One or more errors occurred. (Protocol error(Page.printToPDF): Target closed. (The connection with the server was terminated abnormally)) ---> PuppeteerSharp.TargetClosedException: Protocol error(Page.printToPDF): Target closed. (The connection with the server was terminated abnormally)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.CDPSession.<SendAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Page.<PdfDataAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Page.<PdfAsync>d__150.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HTML2PDF.Console.Program.<SavePDFUsingPuppeteerSharp>d__4.MoveNext() in C:\Sandbox\skaku\HTML2PDF - Copy (2)\HTML2PDF.Console\Program.cs:line 100
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at HTML2PDF.Console.Program.<>c.<Main>b__2_0(Options o) in C:\Sandbox\skaku\HTML2PDF - Copy (2)\HTML2PDF.Console\Program.cs:line 58
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at HTML2PDF.Console.Program.Main(String[] args) in C:\Sandbox\skaku\HTML2PDF - Copy (2)\HTML2PDF.Console\Program.cs:line 42

It works when I run a html with 992 pages and stops working if I add more pages.
Tried in both Windows 10 & windows server 2016
.net core 2.0  console app with latest puppeteer 1.11.1

public static void Main(string[] args)
{
SavePDFUsingPuppeteerSharp(filePath, pdfFilePath).Wait();
}

public static async Task SavePDFUsingPuppeteerSharp(string htmlFilePath, string pdfFilePath)
        {
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true, Timeout = 0 }); //tried without timeout
            var page = await browser.NewPageAsync();
            PdfOptions pdfOptions = new PdfOptions();
            pdfOptions.PreferCSSPageSize = true;
            await page.GoToAsync(htmlFilePath, WaitUntilNavigation.Load);
            await page.PdfAsync(pdfFilePath, pdfOptions);
        }

**Comment by sudheerkaku** [comment]
unfortunately no.. I tried using page range which fixed it, have to find a way to merge byte array or streams.

**Comment by kblok** [comment]
You could also try to do the same on NodeJS and report that there https://github.com/googleChrome/puppeteer

They can improve chrome from there.

**Comment by sudheerkaku** [comment]
will do, do we have a way to merge byte array or streams in puppeteer?

**Comment by kblok** [comment]
I’m afraid you won’t me able to do that. You would get two pdf files (as byte array) each of them have a header. You can’t append one after the other.

**Comment by sudheerkaku** [comment]
ah crap ok, thank you.
