### ISSUE TITLE
TargetClosedException after Puppeteer.ConnectAsync 

### ISSUE THREAD

**Issue by Gdocal** [kblok/puppeteer-sharp#856]
Net framework 4.6.2
Puppeteer version: 1.11.2  (also at least 1.11.1 also affected)
Chrome version: 71.0.3578.98
Windows 10

I use pupeteer for some automation. Program can work for half an hour. I want to be able to reconnect to already opened chrome (opened by puppeteer) in case program crashed or I stopped it to make some changes in code.
My program inject some code JS via  **page.EvaluateOnNewDocumentAsync**
and does a lot of **ClickAsync**, **QuerySelectorAsync,TypeAsync,EvaluateFunctionAsync,XPathAsync,EvaluateExpressionHandleAsync**

The problem is I am not able to reconnect to already opened browser. 
Usually I notice that some automation doesn't work properly. I press red square in VS, change code and start program again. Program tries to connect to last opened chrome url, but after I query **PagesAsync** - I get exception. Details of exception below. **NewPageAsync** doesn't throw exception.

Expected behavior: program shouldn't crash.

I am not able to reproduce this issue in isolated code. I hope you have deeper understanding what can cause exception. 

**TargetClosedException**
Page failed to process Runtime.consoleAPICalled. Delegate to an instance method cannot have null 'this'..    at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at PuppeteerSharp.Page.OnConsoleAPI(PageConsoleResponse message)
   at PuppeteerSharp.Page.<Client_MessageReceived>d__207.MoveNext()

Stack Trace:
  ```
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.CDPSession.<SendAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Page.<CreateAsync>d__200.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Target.<CreatePageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.BrowserContext.<PagesAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Browser.<PagesAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

Page failed to process Runtime.consoleAPICalled. Delegate to an instance method cannot have null 'this'..    at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at PuppeteerSharp.Page.OnConsoleAPI(PageConsoleResponse message)
   at PuppeteerSharp.Page.<Client_MessageReceived>d__207.MoveNext()


Here is my attempt to reproduce it. But actually it doesn't reproduce issue 

```
  private async Task Test()
        {
            Browser browser;
            Page page;
            string fileToSaveSettings = "lastaddr.txt";
            bool openNewBrowser = !File.Exists(fileToSaveSettings);
            string chromePath = @"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe";
        
            if (openNewBrowser)
            { 
                browser = await Puppeteer.LaunchAsync(new LaunchOptions
                {
                    Headless = false,
                    ExecutablePath =chromePath,
                    DefaultViewport = null
                });
                File.WriteAllText(fileToSaveSettings, browser.WebSocketEndpoint);
                var pages = await browser.PagesAsync();
                page = pages.First();
                await page.GoToAsync("https://google.com/");
                var handle = await page.QuerySelectorAsync("a");
                await handle.ClickAsync();
                await page.WaitForNavigationAsync();
                 handle = await page.QuerySelectorAsync("a");
                await handle.ClickAsync();
                await page.WaitForNavigationAsync();

            }
            else
            {
                var endpoint = File.ReadAllText(fileToSaveSettings);
                var connOptions = new ConnectOptions
                {
                    DefaultViewport = null,
                    BrowserWSEndpoint = endpoint,
                };
                browser = await Puppeteer.ConnectAsync(connOptions);
                var pages = await browser.PagesAsync();
                page= pages.First();

            }

        }
Update #1 I tried to use **WaitForRequestAsync, WaitForNavigationAsync, WaitForXPathAsync** to reproduce issue. No luck yet. 

Update #2 
I dug deeper 
Exception occurs here 
```
private Task OnConsoleAPI(PageConsoleResponse message)
        {
            var ctx = _frameManager.ExecutionContextById(message.ExecutionContextId);
            var values = message.Args.Select(ctx.CreateJSHandle).ToArray();  <----------------------------#1
            return AddConsoleMessage(message.Type, values);
        }

internal JSHandle(ExecutionContext context, CDPSession client, RemoteObject remoteObject)
        {
            ExecutionContext = context;
            Client = client;
            Logger = Client.Connection.LoggerFactory.CreateLogger(GetType());  <----------------------------#2
            RemoteObject = remoteObject;
        }
```
NullReference exception.  Client.Connection is null.

Update #3 
The reason of issue is  my injected script via EvaluateOnNewDocumentAsync. It writes some log to console. And this messages sends to puppeteersharp and  probably cause error. After this error occurred, connection get closed and we get exception from Update #2

Update #4 
After I connect to browser or after newbrowser is launched I inject my script again.
When script starts to work  I write message to console.
Currently I get same first message few times in       private Task OnConsoleAPI(PageConsoleResponse message)
First time message processed fine. But on second attempt processing crashed. Crashed because var ctx= _frameManager.ExecutionContextById(message.ExecutionContextId) returns null
and of course ctx.CreateJSHandle(t); throws error. this method used inside delegate in linq.

**Comment by kblok** [comment]
@Gdocal I'm trying to see what's going on there.
Could you do me a favor?
Add a package called `Serilog.Extensions.Logging.File``

Then do something like this
```cs
var factory = new LoggerFactory();
var filter = new FilterLoggerSettings
{
    { "Connection", LogLevel.Trace }
};

factory.WithFilter(filter).AddFile(<SomeFile>, LogLevel.Trace);
```

And pass that factory to the `ConnectAsync` and send me the dump.

**Comment by Gdocal** [comment]
@kblok Thank you
I am still not able to reproduce issue with isolated code. 
[dump-20190128.txt](https://github.com/kblok/puppeteer-sharp/files/2804168/dump-20190128.txt)

**Comment by kblok** [comment]
The issue is there.
```
2019-01-28T17:26:37.3955278+00:00  [VRB] ◀ Receive "{\"method\":\"Runtime.consoleAPICalled\",\"params\":{\"type\":\"log\",\"args\":[{\"type\":\"string\",\"value\":\"Loading js helper\"}],\"executionContextId\":0,\"timestamp\":1548696165925.257,\"stackTrace\":{\"callFrames\":[{\"functionName\":\"\",\"scriptId\":\"21\",\"url\":\"\",\"lineNumber\":10,\"columnNumber\":12},{\"functionName\":\"\",\"scriptId\":\"21\",\"url\":\"\",\"lineNumber\":322,\"columnNumber\":1},{\"functionName\":\"kc\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5185,\"columnNumber\":28},{\"functionName\":\"vi\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5289,\"columnNumber\":80},{\"functionName\":\"a\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5305,\"columnNumber\":63},{\"functionName\":\"\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5306,\"columnNumber\":369},{\"functionName\":\"Vd\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5215,\"columnNumber\":740},{\"functionName\":\"h\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5250,\"columnNumber\":130},{\"functionName\":\"Pf\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5252,\"columnNumber\":481},{\"functionName\":\"Rf\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5254,\"columnNumber\":170},{\"functionName\":\"vg\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5261,\"columnNumber\":134},{\"functionName\":\"wg\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5260,\"columnNumber\":273},{\"functionName\":\"xg\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5263,\"columnNumber\":108},{\"functionName\":\"yg\",\"scriptId\":\"156\",\"url\":\"https://www.googletagmanager.com/gtm.js?id=GTM-P32JX6\",\"lineNumber\":5263,\"columnNumber\":153}]}}}" (00f0de6d)
```

The problem there is that `executionContextId` is `0`. I'll have to take a look at it and see how `puppeteer` (NodeJS) behaves.

**Comment by kblok** [comment]
@Gdocal How are you injecting that script?

**Comment by Gdocal** [comment]
@kblok good to know that you found and understand the root of issue. 
I launch the browser
await Puppeteer.LaunchAsync(new LaunchOptions...
and just execute
 await page.EvaluateOnNewDocumentAsync(_jsHelper);
The problem which I do not understand why I am not able to reproduce the issue with isolated code.
```

    private async Task Test()
        {
            Browser browser;
            Page page;
            string fileToSaveSettings = "lastaddr.txt";
            bool openNewBrowser = !File.Exists(fileToSaveSettings);
            string chromePath = @"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe";

            if (openNewBrowser)
            {
                browser = await Puppeteer.LaunchAsync(new LaunchOptions
                {
                    Headless = false,
                    ExecutablePath = chromePath,
                    DefaultViewport = null
                });
                File.WriteAllText(fileToSaveSettings, browser.WebSocketEndpoint);
                var pages = await browser.PagesAsync();
                page = pages.First();
              
                await page.EvaluateOnNewDocumentAsync("() => {console.log('Loading js helper1');}");
                await page.GoToAsync("https://google.com");


            }
            else
            {
                var factory = new  LoggerFactory();
                var filter = new FilterLoggerSettings
                {
                    { "Connection", LogLevel.Trace }
                };
            
                factory.WithFilter(filter).AddFile("dump.txt", LogLevel.Trace);
                var endpoint = File.ReadAllText(fileToSaveSettings);
                var connOptions = new ConnectOptions
                {
                    
                    DefaultViewport = null,
                    BrowserWSEndpoint = endpoint,
                };
                browser = await Puppeteer.ConnectAsync(connOptions,factory);
                var pages = await browser.PagesAsync();
                page = pages.First();
                await page.EvaluateOnNewDocumentAsync("() => {console.log('Loading js helper2');}");
            }

        }

```

**Comment by kblok** [comment]
I was able to reproduce it also in Node. Let's see what they have to say about this https://github.com/GoogleChrome/puppeteer/issues/3865
