### ISSUE TITLE
Protocol error (Runtime.callFunctionOn): Target closed. 

### ISSUE THREAD

**Issue by calfrei** [kblok/puppeteer-sharp#902]
### Description

Browsing an internal page getting error when Page.WaitForSelectorAsync(...) (I don't think it matter what I do) is executed:

```
Protocol error(Runtime.callFunctionOn): Target closed. (NetworkManager failed to process Network.requestIntercepted. Error converting value "CSPViolationReport" to type 'PuppeteerSharp.ResourceType'. Path 'resourceType'..    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/Src/Newtonsoft.Json/Converters/StringEnumConverter.cs:line 253
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2159
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1032
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2386
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 485
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 167
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer) in /_/Src/Newtonsoft.Json/Linq/JToken.cs:line 2070
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer) in /_/Src/Newtonsoft.Json/Linq/JToken.cs:line 2057
   at PuppeteerSharp.NetworkManager.Client_MessageReceived(Object sender, MessageEventArgs e))
```

### Complete minimal example reproducing the issue

Unfortunately the page is internal but the console shows following errors:

```
index.html [Report Only] Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://*.localhost".

(anonymous) @ index.html [Report Only] Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://*.localhost".
```

Running with following settings

```
List<string> args = new List<string>
{
	"--no-sandbox",
	"--disable-setuid-sandbox",
	"--disable-dev-shm-usage",
	"--disable-accelerated-2d-canvas",
	"--disable-gpu",
	"--disable-infobars",
	$"--window-size={_config.WindowWidth},{_config.WindowHeight}"
};

IgnoreHTTPSErrors = true;
```

### Versions

* PuppeteerSharp v1.11.2
* .NET Core 2.2

**Comment by calfrei** [comment]
Sorry... you can delete this issue...

```
await page.SetBypassCSPAsync(true);
```

fixed it!
